# src/research_crew/config/tasks.yaml
research_task:
  description: >
    Conduct thorough research on company {company} as of {today}. Focus on:
    1. Current company status and health.
    2. Company's financials such as balance sheet, income statement, cash flow statement, etc as of {today}.
    3. Summary of Historical company performance in the last 4 years ending on {today}.
    4. Major challenges and opportunities
    5. Recent news and events
    6. Future outlook and potential developments

    Make sure to organize your findings in a structured format with clear sections.
  expected_output: >
    A comprehensive research document with well-organized sections covering
    all the requested aspects of {company}. Include specific facts, figures,
    and examples where relevant.
  agent: researcher

analysis_task:
  description: >
    Analyze the research findings and create a comprehensive report on {company} as of {today}.
    Your report should:
    1. Begin with an executive summary
    2. Include all key information from the research
    3. Provide insightful analysis of trends and patterns
    4. Offer a market outlook for company, noting that this should not be used for trading decisions
    5. Be formatted in a professional, easy-to-read style with clear headings
  expected_output: >
    A polished, professional report on {company} that presents the research
    findings with added analysis and insights. The report should be well-structured
    with an executive summary, main sections, and conclusion.
  agent: analyst
  context:
    - research_task
  output_file: output/report.md
